# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.
# Welcome to Jekyll!

# ---------------------------------------------------------
# Basic Site Settings
# ---------------------------------------------------------
locale: "en-US"
title: "Home"
title_separator: "—"
name: "Mohsen Monji"
description: "Sociologist & Population Mental Health Researcher"
url: "https://www.mohsenmonji.com"
baseurl: ""                 # empty for custom domain
repository: "mohsenmonji/mohsenmonji.github.io"
permalink: /:categories/:title/

# Minimal Mistakes theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# ---------------------------------------------------------
# Author (used by theme)
# ---------------------------------------------------------
author:
  name: "Mohsen Monji"
  avatar: "images/mohsen-monji-profile.webp" # Replace with your profile picture file   # ensure file exists
  bio: ""
  location: "Tiohtià:ke/Montreal"
  employer: "Concordia University"
  email: "mohsen.monji@concordia.ca"
  # optional: links shown in the sidebar/footer if configured in includes
  # Social media 
  #linkedin: "mohsen-monji-0a3a37269" 
  #github: "Mohsnmonji" 
  #bluesky: "mohsenmonji.bsky.social"
  #orcid: "https://orcid.org/0009-0003-8682-910X"

# ---------------------------------------------------------
# Content Types / Collections
# ---------------------------------------------------------
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# ---------------------------------------------------------
# Defaults
# ---------------------------------------------------------
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: false        # keep in sync with top-level comments setting
      share: true

# ---------------------------------------------------------
# Reading & Build
# ---------------------------------------------------------
include:
  - .htaccess
  - _pages
  - files
  - _posts
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - node_modules
  - tmp

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# ---------------------------------------------------------
# Appearance / Assets
# ---------------------------------------------------------
teaser: "/images/teaser-image.png"             # ensure exists or remove
og_image: "/images/default-social-image.png"   # ensure exists or remove

sass:
  sass_dir: _sass
  style: compressed

# ---------------------------------------------------------
# Plugins
# ---------------------------------------------------------
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache
  # Pagination (optional). If you want pagination, uncomment one of these and configure:
  # - jekyll-paginate
  # or
  # - jekyll-paginate-v2

# Pagination (only if a paginate plugin is enabled)
# paginate: 4
# paginate_path: "/page:num/"

# ---------------------------------------------------------
# Comments (choose a provider or keep disabled)
# ---------------------------------------------------------
comments:
  provider: false
  # For example, to use utterances or giscus, configure here.

# ---------------------------------------------------------
# Social / SEO
# ---------------------------------------------------------
social:
  type: "Person"
  links:
    - "https://twitter.com/mohsenmonji"
    - "https://www.linkedin.com/in/mohsen-monji-0a3a37269"
    - "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"

google_site_verification: ""   # add real code when ready
bing_site_verification: ""
alexa_site_verification: ""
yandex_site_verification: ""

# ---------------------------------------------------------
# Analytics
# ---------------------------------------------------------
analytics:
  provider: "google"
  google:
    # GA4 format (G-XXXXXXXXXX). Leave blank if not using yet.
    measurement_id: "G-XXXXXXXXXX"

# ---------------------------------------------------------
# Archives
# ---------------------------------------------------------
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# ---------------------------------------------------------
# HTML Compression
# ---------------------------------------------------------
compress_html:
  clippings: all
  ignore:
    envs: development

# ---------------------------------------------------------
# Sitemap
# ---------------------------------------------------------
sitemap:
  url: "https://www.mohsenmonji.com"
