# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.
# Welcome to Jekyll!

# Basic Site Settings
locale: "en-US"
title: "Home "
title_separator: "-"
name: "Mohsen Monji"
description: "Sociologist & Population Mental Health Researcher"
url: "https://www.mohsenmonji.com"
baseurl: "" # Leave empty for personal GitHub Pages site
repository: "mohsenmonji/mohsenmonji.github.io"

author: "Mohsen Monji"

# Site Author - Sidebar author details
author:
  avatar: "images/mohsen-monji-profile.webp"
  name: 
  bio:
  location: "Montreal, Canada"
  employer: "Concordia University"
  email: "mohsen.monji@concordia.ca"

  # Social media
  github: "Mohsnmonji"
  orcid: "https://orcid.org/0009-0003-8682-910X"

# Publication Categories
publication_category:
  books:
    title: 'Book Reviews'
  manuscripts:
    title: 'Papers'
  conferences:
    title: 'Conferences'

# Site Settings
teaser: "teaser-image.png"
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
comments:
  provider: false

# SEO Related
google_site_verification: "GOOGLE_VERIFICATION_CODE"
bing_site_verification: "BING_VERIFICATION_CODE"
alexa_site_verification: ""
yandex_site_verification: ""

# Social Sharing
og_image: "default-social-image.png"
social:
  type: "Person"
  links:
    - "https://twitter.com/mohsenmonji"
    - "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"

# Analytics
analytics:
  provider: "google"
  google:
    tracking_id: "UA-XXXXXXXXX-X"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
  - _posts
  
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - node_modules
  - tmp

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults for pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: true
      share: true
      paginate: 4
      paginate_path: "/projects/page:num/"

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Sitemap settings
sitemap:
  url: "https://www.mohsenmonji.com"
